name: transferOnePage

# Controls when the workflow will run
on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: 'x64'
      - name: Install Python requirements mwclient
        run: |
          python -m pip install --upgrade pip
          pip install mwclient
      - env:
          WIKIGG_USER_PASSWORD: ${{ secrets.WIKIGG_USER_PASSWORD}}
          WIKIGG_USER: ${{ secrets.WIKIGG_USER }}
          BWIKI_SESSION_DATA: ${{ secrets.BWIKI_SESSION_DATA}}
        run: python -u ./transferOnePage.py
